### PR TITLE
fix: custom generator for native scalars

### LINKED ISSUE #91: Scalar ID: not being possible to define custom generator
### Describe the Bug

Custom generator defined for Scalar ID seems to be always returning string type:

>

```yml
./cat/cat.mock.ts:
  schema: http://localhost/graphql
  documents:
    - ./cat/queries/*.graphql
  plugins:
    - typescript-mock-data:
        typesFile: "./cat.sdk.ts"
        scalars:
          ID:
            generator: integer
            arguments:
              - 1
              - 100
```

### Generated mock

>

```typescript
export const aCat = (overrides?: Partial<Cat>): Cat => {
  return {
    id:
      overrides && overrides.hasOwnProperty("id")
        ? overrides.id!
        : "f54c0ef5-82b1-4327-8142-8bf4cf1f3a2a",
  };
};
```

>

### What version of graphql-codegen-typescript-mock-data are you using?

> 2.2.5

### What version of Node.js are you using?

> 16.14.0

### PR DESCRIPTION
**Pull request by ardeois**
Only non-native scalars were supported by the `scalars` config. We now check if a custom scalar is defined for each native type

fixes #91

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -101,6 +101,33 @@ const getScalarDefinition = (value: ScalarDefinition | ScalarGeneratorName): Sca
     return value;
 };
 
+const getCustomScalarValue = (customScalar: ScalarDefinition, opts: Options<NamedTypeNode>) => {
+    // If there is a mapping to a `casual` type, then use it and make sure
+    // to call it if it's a function
+    const embeddedGenerator = casual[customScalar.generator];
```
Comment (JimmyPaolini) [inline src/index.ts:107]: I think this feature should also allow for customer `faker` generator functions, I know at least that I would use that features! This is especially necessary if the plan is still to deprecate `casual` in favor of `faker`

Comment (ardeois) [reply src/index.ts:107]: Yes indeed, I think we should do a separate PR to support faker, as it's not directly related

**Review by JimmyPaolini — APPROVED** [review]

File: src/index.ts (hunk 1 above)
Comment (ardeois) [reply src/index.ts:107]: Here is the issue
https://github.com/ardeois/graphql-codegen-typescript-mock-data/issues/97

File: src/index.ts [hunk 2]
```diff
@@ -101,6 +101,33 @@ const getScalarDefinition = (value: ScalarDefinition | ScalarGeneratorName): Sca
...
+    const value = typeof embeddedGenerator === 'function' ? embeddedGenerator(...generatorArgs) : embeddedGenerator;
+
+    if (typeof value === 'string') {
+        return `'${value}'`;
+    }
+    if (typeof value === 'object') {
+        return `${JSON.stringify(value)}`;
+    }
+    return value;
+};
```
Comment (MH4GF) [inline src/index.ts:129]: From the viewpoint of increasing code simplicity, the mock generation of customScalar could also be moved to the MockValueGenerator class. This eliminates the need to import casual in index.ts.
